version: '3.8'
services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload

    ports:
      - "8000:8000"
    environment:
      
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres  # ✅ optional but helpful

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_db:/var/lib/postgresql/data  # ✅ fixed spacing

volumes:
  postgres_db:  # ✅ fixed indentation
