name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: testing  # fixed spelling from "enviroment"
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}_test
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    services:
      postgres:
        image: postgres:13  # Specify a version of PostgreSQL (e.g., 13 or 14)
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}_test
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }} # Ensure a username is defined
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    runs-on: ubuntu-latest  # fixed spelling from "ubuntu-lastest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # updated version

      - name: Setup Python
        uses: actions/setup-python@v5  # latest version
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pytest
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # or your test command
